# Generated by Django 2.2.2 on 2019-06-27 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_auto_20190627_1909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.FilePathField(default='static/images/pro.jpg', path='static/images/'),
        ),
    ]
