# Generated by Django 2.2.3 on 2019-07-29 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_project_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='app_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
