# Generated by Django 2.2.3 on 2019-07-31 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_project_app_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='order_id',
            field=models.IntegerField(default=99),
        ),
    ]
